// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: getFeeds.sql

package database

import (
	"context"
)

const getFeeds = `-- name: GetFeeds :one
SELECT id, created_at, updated_at, name, url, user_id FROM feeds
`


func (q *Queries) GetFeeds(ctx context.Context) ([]Feed, error) {
    rows, err := q.db.QueryContext(ctx, getFeeds)
    if err != nil {
        return nil, err
    }
    defer rows.Close()

    var feeds []Feed
    for rows.Next() {
        var f Feed
        err := rows.Scan(
            &f.ID,
            &f.CreatedAt,
            &f.UpdatedAt,
            &f.Name,
            &f.Url,
            &f.UserID,
        )
        if err != nil {
            return nil, err
        }
        feeds = append(feeds, f)
    }

    if err := rows.Err(); err != nil {
        return nil, err
    }

    return feeds, nil
}
